apiVersion: v1
kind: Service
metadata:
  name: promock
  labels:
    app: metrics
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: promock

