apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempy-prometheus-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: tempy-prometheus-adapter
        image: quay.io/rzago/tempy-prometheus-adapter:0.1
        ports:
        - containerPort: 9090

